[project]
name = "web-rag"
version = "0.1.0"
description = "Simple RAG over the web."
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "googlesearch-python>=1.2.5",
    "haystack-ai>=2.5.1",
    "sentence-transformers>=3.1.1",
    "trafilatura>=1.12.2",
    "typer>=0.12.5",
]
